import { Body } from '@react-email/body'
import { Button } from '@react-email/button'
import { Container } from '@react-email/container'
import { Head } from '@react-email/head'
import { Heading } from '@react-email/heading'
import { Hr } from '@react-email/hr'
import { Html } from '@react-email/html'
import { Img } from '@react-email/img'
import { Preview } from '@react-email/preview'
import { Section } from '@react-email/section'
import { Tailwind } from '@react-email/tailwind'
import { Text } from '@react-email/text'

export interface LoanShareProps {
  username: string
  sharer: string
  loanAmount: number
  loanName: string
  months: number
}

export default function LoanShareEmail({
  username = 'Fran Bosquet',
  sharer = 'Other User',
  loanName = 'Car loan',
  loanAmount = 10000,
  months = 60
}: LoanShareProps) {
  return (
    <Html>
      <Head />
      <Preview>{sharer} wants to share a loan with you</Preview>
      <Tailwind>
        <Body className="bg-gradient-to-b from-slate-950 to-slate-700 my-auto mx-auto">
          <Container className="bg-slate-200 border border-solid border-slate-100 rounded-lg my-[40px] mx-auto p-[20px] w-[465px] font-sans">
            <Section className="mt-[32px]">
              <Img
                src={'https://expentrac.app/logo.svg'}
                width="40"
                height="40"
                alt="Expentrac Logo"
                className="mx-auto"
              />
            </Section>
            <Heading className="text-black text-[24px] font-normal text-center p-0 my-[30px] mx-0">
              Hey {username}
            </Heading>
            <Text className="text-black text-[14px] leading-[24px]">
              {sharer} wants to share a loan with you. The loan in question is:
            </Text>
            <Text className="text-black text-[20px] leading-[24px] text-center">
              <strong>{loanName}</strong>
            </Text>
            <Text className="text-black text-[14px] leading-[24px]">
              Monthly fee for this loan is <strong>{new Intl.NumberFormat('en-UK', { style: 'currency', currency: 'EUR' }).format(loanAmount)}</strong>. Its going to last <strong>{months}</strong> months. You can accept or reject the loan in your notifications section.
            </Text>
            <Section className="mt-[24px] mb-[24px] flex justify-center">
              <Button
                pX={20}
                pY={12}
                className="bg-[#000000] rounded text-white text-[12px] font-semibold no-underline text-center"
                href='https://www.expentrac.app/dashboard/notifications'
              >
                Your notifications centre
              </Button>
            </Section>
            <Hr className="border border-solid border-[#eaeaea] my-[26px] mx-0 w-full" />
            <Text className="text-[#666666] text-[12px] leading-[24px]">
              This email was automatically generated by <strong>Expentrac</strong>. If you don&rsquo;t want to receive emails from us, please modify your email preferences in your <a href='https://www.expentrac.app/dashboard/user' target='_blank' rel="noreferrer" >account settings</a>.
            </Text>
          </Container>
        </Body>
      </Tailwind>
    </Html>
  )
}
