import { Body } from '@react-email/body'
import { Button } from '@react-email/button'
import { Container } from '@react-email/container'
import { Head } from '@react-email/head'
import { Heading } from '@react-email/heading'
import { Hr } from '@react-email/hr'
import { Html } from '@react-email/html'
import { Img } from '@react-email/img'
import { Preview } from '@react-email/preview'
import { Section } from '@react-email/section'
import { Tailwind } from '@react-email/tailwind'
import { Text } from '@react-email/text'

interface Props {
  username: string
}

export default function WelcomeEmail({
  username = 'Fran Bosquet'
}: Props) {
  return (
    <Html>
      <Head />
      <Preview>preview text</Preview>
      <Tailwind>
        <Body className="bg-gradient-to-b from-slate-950 to-slate-700 my-auto mx-auto">
          <Container className="bg-slate-200 border border-solid border-slate-100 rounded-lg my-[40px] mx-auto p-[20px] w-[465px] font-sans">
            <Section className="mt-[32px]">
              <Img
                src={'https://expentrac.app/logo.svg'}
                width="40"
                height="40"
                alt="Expentrac Logo"
                className="mx-auto"
              />
            </Section>
            <Heading className="text-black text-[24px] font-normal text-center p-0 my-[30px] mx-0">
              Welcome {username}
            </Heading>
            <Text className="text-black text-[14px] leading-[24px]">
              This is <strong>Fran</strong>, from <strong>Expentrac</strong>
            </Text>
            <Text className="text-black text-[14px] leading-[24px]">
              Thank you very much for giving us a try! We are very excited to onboard new users like you. Im working hard to make <strong>Expentrac</strong> the best expense tracker possible. I hope you enjoy it!
            </Text>
            <Text className="text-black text-[14px] leading-[24px]">
              You can start by jumping straight to your dashboard and start adding your expenses. If you have any questions, please feel free to reach <a href="https:x.com/frbosquet" target='_blank' rel="noreferrer">out to me at X</a>.
            </Text>
            <Section className="mt-[24px] mb-[24px] flex justify-center">
              <Button
                pX={20}
                pY={12}
                className="bg-[#000000] rounded text-white text-[12px] font-semibold no-underline text-center mr-[12px]"
                href='https://www.expentrac.app/dashboard/loans'
              >
                Add a loan
              </Button>
              <Button
                pX={20}
                pY={12}
                className="bg-[#000000] rounded text-white text-[12px] font-semibold no-underline text-center"
                href='https://www.expentrac.app/dashboard/subscriptions'
              >
                Add a subscription
              </Button>
            </Section>
            <Hr className="border border-solid border-[#eaeaea] my-[26px] mx-0 w-full" />
            <Text className="text-[#666666] text-[12px] leading-[24px]">
              This email was automatically generated by <strong>Expentrac</strong>. If you don&rsquo;t want to receive emails from us, please modify your email preferences in your <a href='https://www.expentrac.app/dashboard/user' target='_blank' rel="noreferrer" >account settings</a>.
            </Text>
          </Container>
        </Body>
      </Tailwind>
    </Html>
  )
}
